# Generated by Django 5.2.15 on 2026-06-08 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_project_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id_badge', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('delivery', 'Delivery'), ('quality', 'Quality'), ('teamwork', 'Teamwork'), ('milestone', 'Milestone')], default='delivery', max_length=20)),
                ('tier', models.PositiveSmallIntegerField(default=1)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('xp_reward', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'badge',
                'ordering': ['category', 'tier', 'code'],
            },
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id_user_stats', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='gamification_stats', to='core.useraccount')),
            ],
            options={
                'db_table': 'user_stats',
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id_user_badge', models.BigAutoField(primary_key=True, serialize=False)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('progress', models.IntegerField(blank=True, null=True)),
                ('badge', models.ForeignKey(db_column='id_badge', on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='core.badge')),
                ('project', models.ForeignKey(blank=True, db_column='id_project', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='core.project')),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='core.useraccount')),
            ],
            options={
                'db_table': 'user_badge',
                'ordering': ['-unlocked_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('project__isnull', False)), fields=('user', 'badge', 'project'), name='unique_user_badge_per_project'), models.UniqueConstraint(condition=models.Q(('project__isnull', True)), fields=('user', 'badge'), name='unique_user_badge_global')],
            },
        ),
    ]
